### PR TITLE
Branch2

### PR DESCRIPTION
**Pull request by npostavs**
checking if "Allow edits from maintainers" default is sticky

### CODE REVIEW

**Comment by npostavs** [comment]
Seems not to be sticky, I still see the "Allow edits from maintainers" box checked when I make a new pull request.

**Comment by tarsius** [comment]
I don't understand.

Can or can you not tick/untick the box after creating the pull request (without an error about that currently not being possible).

Or are you saying that even if you untick that *before* making the pr that it is still ticked once you look at the created pr?

**Comment by npostavs** [comment]
Oh, I was just testing the "default" setting, i.e., this:

> I think it used to be the case that this never worked for master or at least that the user had to explicitly allow this after creating a pull-request that uses that branch as source, while for other branches the default setting was used and the default setting is "allow" by, uhm, default.

---

I've now tried changing the tick on this pr, I get `You can't perform that action at this time.`, but it still works (!).

**Comment by tarsius** [comment]
> Oh, I was just testing the "default" setting

So the default is "allow" and telling github to "not allow" only affect the pr for which this is done, i.e. it is not "sticky". Well, that's not so nice for people who don't want that, but it is nice for maintainers like me who like to be able to push to the fork.

> I've now tried changing the tick on this pr, I get `You can't perform that action at this time.`, but it still works (!).

That at least explains why the relevant setting didn't show up in my diffs. I was told that my actions had no effect when in fact they had.

**Pull request closed without merging**
